const types = {
  SET_ALERT: "SET_ALERT",
  REMOVE_ALERT: "REMOVE_ALERT",
  HIDE_ALERT: "HIDE_ALERT",
  REGISTER: "REGISTER",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  VIEW_SPINNER: "VIEW_SPINNER",
  HIDE_SPINNER: "Hide_SPINNER"
};

export default types;
